name: ${project.name}
author: nextRound
main: de.nextround.nextcolors.NextColors
version: ${project.version}
softdepend: [PlotSquared]
description: ${project.description}
website: ${project.url}
commands:
  nc:
  ncu:
api-version: 1.19